[package]
name = "hakelig"
version = "0.0.1"
authors = ["Andreas Rottmann <mail@r0tty.org>"]
edition = "2018"

[dependencies]
failure = "0.1"
futures = "0.1"
tokio = "0.1"
url = "1.7"
html5ever = "0.22"
tendril = "0.4.1"
#reqwest = "0.9.11"
